# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - build

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: warn

lint:
  stage: test
  image: python:3.11-slim-bookworm
  before_script:
    - pip install --no-cache-dir ruff
  script:
    - ruff check .
    - ruff format --check .

tests:
  stage: test
  image: python:3.11-slim-bookworm
  before_script:
    - pip install --no-cache-dir -r requirements-dev.txt
  script:
    - pytest -v

docker-build-master:
  # Official docker image.
  image: jdrouet/docker-with-buildx
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/amd64,linux/arm64 --pull --push -t "$CI_REGISTRY_IMAGE" .
  only:
    - master
